source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'Outlay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  # Pods for Outlay

end
