import Foundation
import UIKit

class Constants {
    static let outlayTitle = "Outlay"
    static let newExpenceTitle = "New expense"
    static let expenseCellIdentifier = "ExpenseCell"
    static let monthCircleLabelText = "Month"
    static let todayCircleLabelText = "Today"
    static let weekCircleLabelText = "Week"
    static let strideDayIncrement: Date.Stride = 60*60*24
    static let addMonthBudgetButtonTitle = "Set budget"
    static let todayOutlayBudgetLabelText = "Budget: "
    static let todayOutlaySpentLabelText = "Spent: "
    static let todayOutlayAvailableLabelText = "Available: "
    static let weekOutlayBudgetLabelText = "Budget: "
    static let weekOutlaySpentLabelText = "Spent: "
    static let weekOutlayAvailableLabelText = "Available: "
    static let monthOutlayBudgetLabelText = "Expenses budget: "
    static let monthOutlaySpentLabelText = "Money spent: "
    static let backgroundAppColor = UIColor.systemGroupedBackground
    static let lightBlueColor = UIColor(red: 2/255, green: 177/255, blue: 242/255, alpha: 1.0)
    static let darkBlueColor = UIColor(red: 0/255, green: 90/255, blue: 190/255, alpha: 1.0)
    static let darkStrokeBlueColor = UIColor(red: 0/255, green: 90/255, blue: 190/255, alpha: 0.8)
    static let dateFormatYMDHMS = "yyyy-MM-dd'T'HH:mm:ssZ"
    static let dateFormatDMY = "d.MM.yyyy"
    static let continueButton = "Continue"
    static let signUp = "Sign Up"
    static let signIn = "Sign In"
    static let forgotPassword = "Forgot Password"
    static let resetPassword = "Reset password"
    static let email = "Email"
    static let password = "Password"
    static let confirmPassword = "Confirm password"
    static let settings = "Settings"
    static let error = "Error"
    static let cancel = "Cancel"
    static let invalidFieldsInserted = "Please fill all the fields correctly"
    static let unknownError = "Unknown error"
    static let unknownDate = "Unknown date"
    static let logOut = "Log out"
    static let defaultLeftInset = 18
    static let defaultRightInset = 18
    static let defaultTopInset = 18
    static let defaultBottomInset = 18
    static let tableViewCellLeftInset = 10
    static let tableViewCellRightInset = 10
    static let tableViewCellTopInset = 5
    static let tableViewCellBottomInset = 5
    static let newExpenseTitleLabelField = "Title"
    static let newExpenseTitleTextField = "Enter title"
    static let newExpenseCategoryLabelField = "Category"
    static let newExpenseCategoryTextField = "Choose category"
    static let newExpensePriceLabelField = "Price"
    static let newExpensePriceTextField = "Enter price"
    static let successDataInsert = "Data was successfuly inserted"
    static let saveNewExpenseBtnTouched = "Save new expence touched"
    static let calendarImage = "calendar"
    static let addNewExpenseTitle = "Insert expence"
}
